# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"conceptual_weight": "model.ipynb",
         "coco_weight": "model.ipynb",
         "get_device": "model.ipynb",
         "MLP": "model.ipynb",
         "ClipCaptionModel": "model.ipynb",
         "ClipCaptionPrefix": "model.ipynb",
         "generate_beam": "model.ipynb",
         "generate2": "model.ipynb",
         "inference": "model.ipynb",
         "N": "model.ipynb",
         "V": "model.ipynb",
         "ARRAY": "model.ipynb",
         "ARRAYS": "model.ipynb",
         "VS": "model.ipynb",
         "VN": "model.ipynb",
         "VNS": "model.ipynb",
         "T": "model.ipynb",
         "TS": "model.ipynb",
         "TN": "model.ipynb",
         "TNS": "model.ipynb",
         "TSN": "model.ipynb",
         "TA": "model.ipynb",
         "D": "model.ipynb",
         "CPU": "model.ipynb",
         "CUDA": "model.ipynb",
         "is_gpu": "model.ipynb",
         "device": "model.ipynb",
         "tokenizer": "model.ipynb"}

modules = ["model.py"]

doc_url = "https://{user}.github.io/clip2textgen/"

git_url = "https://github.com/{user}/clip2textgen/tree/{branch}/"

def custom_doc_links(name): return None
