# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"conceptual_weight": "00_model.ipynb",
         "coco_weight": "00_model.ipynb",
         "get_device": "00_model.ipynb",
         "MLP": "00_model.ipynb",
         "ClipCaptionModel": "00_model.ipynb",
         "ClipCaptionPrefix": "00_model.ipynb",
         "generate_beam": "00_model.ipynb",
         "generate2": "00_model.ipynb",
         "inference": "00_model.ipynb",
         "N": "00_model.ipynb",
         "V": "00_model.ipynb",
         "ARRAY": "00_model.ipynb",
         "ARRAYS": "00_model.ipynb",
         "VS": "00_model.ipynb",
         "VN": "00_model.ipynb",
         "VNS": "00_model.ipynb",
         "T": "00_model.ipynb",
         "TS": "00_model.ipynb",
         "TN": "00_model.ipynb",
         "TNS": "00_model.ipynb",
         "TSN": "00_model.ipynb",
         "TA": "00_model.ipynb",
         "D": "00_model.ipynb",
         "CPU": "00_model.ipynb",
         "CUDA": "00_model.ipynb",
         "is_gpu": "00_model.ipynb",
         "device": "00_model.ipynb",
         "tokenizer": "00_model.ipynb"}

modules = ["model.py"]

doc_url = "https://{user}.github.io/clip2textgen/"

git_url = "https://github.com/{user}/clip2textgen/tree/{branch}/"

def custom_doc_links(name): return None
